name: Github CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Installation Environment
        uses: actions/setup-node@master
        with:
          node-version: 16.x

      - name: Installation
        uses: borales/actions-yarn@master
        with:
          cmd: install

      - name: Build
        uses: borales/actions-yarn@master
        with:
          cmd: build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist
